const desktopActions = {
  TOGGLE_START_MENU: 'TOGGLE_START_MENU',
  CLOSE_WINDOW: 'CLOSE_WINDOW',
  OPEN_WINDOW: 'OPEN_WINDOW',
  SET_WINDOW_ACTIVE: 'SET_WINDOW_ACTIVE',
};

export default desktopActions;
